### ISSUE TITLE
关于 proxy 的配置和GDAL windows 版的安装问题

### ISSUE THREAD

**Issue by Tiramisu023** [cutecore/google_map_satellite_download#1]
楼主您好，感谢您提供的脚本工具。因为我没有接触过这方面的知识，所以想请教下您：
1. google 的 proxy 具体需要如何获得并配置呢？
2. 在安装 GDAL windows 版时，是否需要先安装 microsoft Visual Studio 呢？

谢谢您~

**Comment by cutecore** [comment]
1. 你需要有“科学“上网，代理软件会有一个http代理地址，比如v2ray是127.0.0.1:10809
2. 不需要安装 microsoft Visual Studio，下载页面的MSVC 2017，指的是发布者 编译 时候用的环境。
2.1 很多软件比如Apache HTTP Server，发布的只有源代码，需要自己编译，这时候会有一些爱好者，会自己编译发布，
并表明编译环境。
> The Apache HTTP Server Project itself does not provide binary releases of software, only source code. Individual committers > may provide binary packages as a convenience, but it is not a release deliverable.
> If you cannot compile the Apache HTTP Server yourself, you can obtain a binary package from numerous binary distributions available on the Internet.
> Popular options for deploying Apache httpd, and, optionally, PHP and MySQL, on Microsoft Windows, include:
2.2 下载那个release-1916-x64-gdal-3-3-3-mapserver-7-6-4.zip就可以，然后配置环境变量
